import re
string1=input("enter your desired string ")
m=re.search(r"\d+",string1)
t=re.match(r"\d",string1)
p=re.findall(r"\d+",string1)
q=re.sub(r"\d+","NUMBER HERE",string1)
r=re.split(r"[,;\s]+",string1)
print(m.group())
print(m.start(),m.end())
print(t)
print(p)
print(q)
print(r)
print("program end ")
